import { StyleSheet } from "react-native";

const mainColor = "#7b2cbf";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    /*     width: "100%",
    height: "100%",
    position: "absolute", */
  },
  image: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: "100%",
    zIndex: 999,
  },
  mainContainer: {
    alignItems: "center",
    backgroundColor: "#fafafa",
    position: "absolute",
    zIndex: 9999,
    top: "5%",
    width: "90%",
    height: "77%",
    left: "5%",
  },
  titleContainer: {
    alignItems: "center",
    position: "absolute",
    top: 80,
  },
  btnConfig: {
    backgroundColor: mainColor,
    borderRadius: 5,
    width: 150,
    height: 60,
    position: "absolute",
    top: 250,
  },
  btnRules: {
    backgroundColor: mainColor,
    borderRadius: 5,
    width: 150,
    height: 60,
    position: "absolute",
    top: 350,
  },
  btnStart: {
    backgroundColor: mainColor,
    borderRadius: 5,
    width: 150,
    height: 60,
    position: "absolute",
    top: 450,
  },
  insideBtnTextView: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  view1: {
    backgroundColor: "gray",
    position: "absolute",
    width: 78,
    height: 78,
    left: "3%",
    top: "86%",
    flex: 1,
    alignItems: "center",
  },
  view1txt: {
    color: "#2e2e2e",
    top: -30,
    fontSize: 14,
  },
  view1txt1: { color: "#fafafa", fontSize: 24 },

  view2: {
    backgroundColor: "gray",
    position: "absolute",
    width: 78,
    height: 78,
    left: "27.3%",
    top: "86%",
    alignItems: "center",
  },
  view2txt: {
    color: "#2e2e2e",
    top: -30,
    fontSize: 14,
  },
  view1txt2: { color: "#fafafa", fontSize: 24 },
  view3: {
    backgroundColor: "gray",
    position: "absolute",
    width: 78,
    height: 78,
    right: "27.3%",
    top: "86%",
    alignItems: "center",
  },
  view3txt: {
    color: "#2e2e2e",
    top: -30,
    fontSize: 14,
  },
  view4: {
    backgroundColor: "gray",
    position: "absolute",
    width: 78,
    height: 78,
    right: "3%",
    top: "86%",
    alignItems: "center",
  },
  view4txt: {
    color: "#2e2e2e",
    top: -30,
    fontSize: 14,
  },
});
