import { StyleSheet } from "react-native";

const mainColor = "#7b2cbf";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  image: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: "100%",
    zIndex: 999,
  },
  mainContainer: {
    alignItems: "center",
    backgroundColor: "#fafafa",
    position: "absolute",
    zIndex: 9999,
    top: "5%",
    width: "90%",
    height: "77%",
    left: "5%",
  },
  titleContainer: {
    alignItems: "center",
    position: "absolute",
    top: "12%",
  },
  btnConfig: {
    backgroundColor: mainColor,
    borderRadius: 5,
    width: "40%",
    aspectRatio: 2.5,
    position: "absolute",
    top: "35%",
  },
  btnRules: {
    backgroundColor: mainColor,
    borderRadius: 5,
    width: "40%",
    aspectRatio: 2.5,
    position: "absolute",
    top: "50%",
  },
  btnStart: {
    backgroundColor: mainColor,
    borderRadius: 5,
    width: "40%",
    aspectRatio: 2.5,
    position: "absolute",
    top: "65%",
  },
  insideBtnTextView: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  view1holder: {
    backgroundColor: "red",
    position: "absolute",
    width: "21.25%",
    aspectRatio: 0.7,
    left: "3%",
    bottom: "2.5%",
  },
  view1: {
    backgroundColor: "gray",
    position: "absolute",
    width: "100%",
    aspectRatio: 1,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  view1up: {
    position: "absolute",
    width: "100%",
    backgroundColor: "blue",
    top: "0%",
    alignItems: "center",
    justifyContent: "center",
  },
  view1txt: {
    color: "#2e2e2e",
    fontSize: 14,
  },
  view1txt1: { color: "#fafafa", fontSize: 24 },

  view2: {
    backgroundColor: "gray",
    position: "absolute",
    width: "21.25%",
    aspectRatio: 1,
    left: "27.25%",
    bottom: "2.5%",
    alignItems: "center",
    justifyContent: "center",
  },
  view2up: {
    position: "absolute",
    width: "21.25%",
    left: "27.25%",
    height: "3.5%",
    backgroundColor: "red",
    bottom: "15.5%",
    alignItems: "center",
    justifyContent: "center",
  },
  view2txt: {
    color: "#2e2e2e",
    fontSize: 14,
  },
  view1txt2: { color: "#fafafa", fontSize: 24 },
  view3: {
    backgroundColor: "gray",
    position: "absolute",
    width: "21.25%",
    aspectRatio: 1,
    right: "27.25%",
    bottom: "2.5%",
    alignItems: "center",
    justifyContent: "center",
  },
  view3up: {
    position: "absolute",
    width: "21.25%",
    right: "27.25%",
    height: 20,
    top: "82%",
    alignItems: "center",
    justifyContent: "center",
  },
  view3txt: {
    color: "#2e2e2e",
    fontSize: 14,
  },
  view4: {
    backgroundColor: "gray",
    position: "absolute",
    width: "21.25%",
    aspectRatio: 1,
    right: "3%",
    bottom: "2.5%",
    alignItems: "center",
    justifyContent: "center",
  },
  view4up: {
    position: "absolute",
    width: "21.25%",
    aspectRatio: 1,
    right: "3%",
    height: 20,
    top: "82%",
    alignItems: "center",
    justifyContent: "center",
  },
  view4txt: {
    color: "#2e2e2e",
    fontSize: 14,
  },
});
